import turtle
turtle.shape('turtle')
turtle.penup()
turtle.backward(300)
turtle.pendown()
turtle.speed(0.5)
def line(x1, x2, y2):
    turtle.pendown()
    turtle.goto(turtle.pos()+ (x2, y2))
    turtle.penup()
a=60
d={'1': (turtle.penup(),
         turtle.goto(turtle.pos()+(0, a)),
         line(turtle.pos(), a, a),
         line(turtle.pos(), 0, -2*a),
         turtle.penup(),
         turtle.goto(turtle.pos()+(a/4, 0))),
   '0': (line(turtle.pos(), 0, a+a),
         line(turtle.pos(), a, 0),
         line(turtle.pos(), -0, -2*a),
         line(turtle.pos(), -a, 0),
         turtle.penup(),
         turtle.goto(turtle.pos()+ (a*1.25, 0))),
   '2': (turtle.penup(),
         turtle.goto(turtle.pos()+ (0, 2*a)),
         turtle.pendown(),
         line(turtle.pos(), a, 0),
         line(turtle.pos(), -0, -a),
         line(turtle.pos(), -a, -a),
         line(turtle.pos(), a, 0),
         turtle.penup(),
         turtle.goto(turtle.pos()+ (a/4, 0))),
   '4': (turtle.penup(),
         turtle.goto(turtle.pos()+ (0, 2*a)),
         turtle.pendown(),
         line(turtle.pos(), 0, -a),
         line(turtle.pos(), a, 0),
         line(turtle.pos(), 0, a),
         line(turtle.pos(), 0, -2*a),
         turtle.penup(),
         turtle.goto(turtle.pos()+ (a/4, 0))),
   '3': (line(turtle.pos(), a, a),
         line(turtle.pos(), -a, 0),
         line(turtle.pos(), a, a),
         line(turtle.pos(), -a, 0),
         turtle.penup(),
         turtle.goto(turtle.pos()+ (a*1.25, -a-a))),
   '5': (line(turtle.pos(), a, 0),
         line(turtle.pos(), 0, a),
         line(turtle.pos(), -a, 0),
         line(turtle.pos(), 0, a),
         line(turtle.pos(), a, 0),
         turtle.penup(),
         turtle.goto(turtle.pos()+ (a/4, -2*a))),
   '6': (turtle.penup(),
         turtle.goto(turtle.pos()+ (a, 2*a)),
         turtle.pendown(),
         line(turtle.pos(), -a, -a),
         line(turtle.pos(), -0, -a),
         line(turtle.pos(), a, 0),
         line(turtle.pos(), 0, a),
         line(turtle.pos(), -a, 0),
         turtle.penup(),
         turtle.goto(turtle.pos()+ (a*1.25, -a))),
   '7': (line(turtle.pos(), 0, a),
         line(turtle.pos(), a, a),
         line(turtle.pos(), -a, 0),
         turtle.penup(),
         turtle.goto(turtle.pos()+ (a*1.25, -2*a))),
   '8': (line(turtle.pos(), 0, 2*a),
         line(turtle.pos(), a, 0),
         line(turtle.pos(), 0, -2*a),
         line(turtle.pos(), -a, 0),
         line(turtle.pos(), 0, a),
         line(turtle.pos(), a, 0),
         line(turtle.pos(), 0, -a),
         turtle.penup(),
         turtle.goto(turtle.pos()+ (a/4, 0))),
   '9': (line(turtle.pos(), a, a),
         line(turtle.pos(), -0, a),
         line(turtle.pos(), -a, 0),
         line(turtle.pos(), 0, -a),
         line(turtle.pos(), a, 0),
         turtle.penup(),
         turtle.goto(turtle.pos()+ (a/4, -a))),
   }
d['1']

